[package]
name = "Spendlite-API"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
chrono = "0.4.41"
jsonwebtoken = "9.3.1"
serde = { version = "1.0.219", features = ["derive"] }
tokio = "1.45.0"
utoipa = "5.3.1"
utoipa-swagger-ui = { version = "8", features = ["axum"] }
